-- Run this once in your Supabase project's SQL Editor
-- (Project dashboard -> SQL Editor -> New query -> paste -> Run)
--
-- Adds a per-team opponent contacts list, visible and editable only by
-- approved editors (same allowlist that already gates adding/editing
-- games). Safe to run more than once.

create table if not exists opponent_contacts (
  id bigint generated by default as identity primary key,
  team text not null,
  club text not null default '',
  contact text not null default '',
  email text not null default '',
  scheduled text not null default 'No' check (scheduled in ('Yes', 'No', 'Contact Made')),
  created_at timestamptz not null default now()
);

alter table opponent_contacts enable row level security;

drop policy if exists "Approved editors can read opponent contacts" on opponent_contacts;
create policy "Approved editors can read opponent contacts"
  on opponent_contacts for select
  using (
    exists (
      select 1 from approved_editors
      where approved_editors.email = auth.jwt() ->> 'email'
    )
  );

drop policy if exists "Approved editors can insert opponent contacts" on opponent_contacts;
create policy "Approved editors can insert opponent contacts"
  on opponent_contacts for insert
  with check (
    exists (
      select 1 from approved_editors
      where approved_editors.email = auth.jwt() ->> 'email'
    )
  );

drop policy if exists "Approved editors can update opponent contacts" on opponent_contacts;
create policy "Approved editors can update opponent contacts"
  on opponent_contacts for update
  using (
    exists (
      select 1 from approved_editors
      where approved_editors.email = auth.jwt() ->> 'email'
    )
  );

drop policy if exists "Approved editors can delete opponent contacts" on opponent_contacts;
create policy "Approved editors can delete opponent contacts"
  on opponent_contacts for delete
  using (
    exists (
      select 1 from approved_editors
      where approved_editors.email = auth.jwt() ->> 'email'
    )
  );
